# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
#

options:
  exporter-port:
    type: int
    default: 10000
    description: |
      Start the prometheus exporter at "exporter-port". By default, it will
      start at port 10000.
  exporter-log-level:
    type: string
    default: "INFO"
    description: |
      Start the prometheus exporter with log level "exporter-log-level". By
      default, it will set to INFO. Allowed values are "DEBUG", "INFO",
      "WARNING", "ERROR", "CRITICAL". Values other than those will result in
      failure of the exporter.
