# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
#

options:
  exporter-port:
    type: int
    default: 10000
    description: |
      Start the prometheus exporter at "exporter-port". By default, it will
      start at port 10000. Note that this configuration can only be set at
      deployment time, changing this config value will take no effects.

