groups:

- name: LSI SAS-2 controller
  rules:

  - alert: Sas2ircuCommandFailed
    expr: sas2ircu_command_success == 0
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: Failed to run sas2ircu. (instance {{ $labels.instance }})
      description: |
        Failed to get LSI SAS-2 controller information using sas2ircu.
          INSTANCE = {{ $labels.instance }}
          SUCCESS = {{ $value }}
          LABELS = {{ $labels }}

  - alert: LSISAS2ControllerNotFound
    expr: lsi_sas_2_controllers == 0
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: LSI SAS-2 controller not found. (instance {{ $labels.instance }})
      description: |
        Cannot found LSI SAS-2 controller on this host machine.
          INSTANCE = {{ $labels.instance }}
          NUMBER_OF_CONTROLLERS = {{ $value }}
          LABELS = {{ $labels }}

  - alert: LSISAS2IRVolumeNotFound
    expr: lsi_sas_2_ir_volumes == 0
    for: 0m
    labels:
      severity: warning
      controller_id: 0
      instance: ubuntu-2
    annotations:
      summary: LSI SAS-2 IR volume not found. (instance {{ $labels.instance }})
      description: |
        Cannot found LSI SAS-2 integrated RAID volumes on this controller.
          CONTROLLER_ID = {{ $labels.controller_id }}
          NUMBER_OF_VOLUMES = {{ $value }}
          LABELS = {{ $labels }}

  - alert: LSISAS2IRVolumeUnready
    expr: lsi_sas_2_ir_volume_info{status !~ "Okay.*"} == 1
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: LSI SAS-2 volume is not ready. (instance {{ $labels.instance }})
      description: |
        LSI SAS-2 volume is not in "Okay" state. Please check the if the volume is working as expected.
          CONTROLLER_ID = {{ $labels.controller_id }}
          VOLUME_ID = {{ $labels.volume_id}}
          STATUS = {{ $labels.status }}
          LABELS = {{ $labels }}

  - alert: LSISAS2PhysicalDiskUnready
    expr: lsi_sas_2_physical_device_info{state !~ "(Ready.*|Optimal.*)"} == 1
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: LSI SAS-2 physical disk is not ready. (instance {{ $labels.instance }})
      description: |
        LSI SAS-2 physical disk not in "Ready" or "Optimal" state. Please check the if the physical disk is working as expected.
          CONTROLLER_ID = {{ $labels.controller_id }}
          ENCLOSURE_ID = {{ $labels.enclosure_id }}
          SLOT_ID = {{ $labels.slot_id }}
          STATE = {{ $labels.state }}
          LABELS = {{ $labels }}
