groups:

- name: LSI SAS-3 controller
  rules:

  - alert: Sas3ircuCommandFailed
    expr: sas3ircu_command_success == 0
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: Failed to run sas3ircu. (instance {{ $labels.instance }})
      description: |
        Failed to get LSI SAS-3 controller information using sas3ircu.
          INSTANCE = {{ $labels.instance }}
          SUCCESS = {{ $value }}
          LABELS = {{ $labels }}

  - alert: LSISAS3ControllerNotFound
    expr: lsi_sas_3_controllers == 0
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: LSI SAS-3 controller not found. (instance {{ $labels.instance }})
      description: |
        Cannot found LSI SAS-3 controller on this host machine.
          INSTANCE = {{ $labels.instance }}
          NUMBER_OF_CONTROLLERS = {{ $value }}
          LABELS = {{ $labels }}

  - alert: LSISAS3IRVolumeNotFound
    expr: lsi_sas_3_ir_volumes == 0
    for: 0m
    labels:
      severity: warning
      controller_id: 0
      instance: ubuntu-2
    annotations:
      summary: LSI SAS-3 IR volume not found. (instance {{ $labels.instance }})
      description: |
        Cannot found LSI SAS-3 integrated RAID volumes on this controller.
          CONTROLLER_ID = {{ $labels.controller_id }}
          NUMBER_OF_VOLUMES = {{ $value }}
          LABELS = {{ $labels }}

  - alert: LSISAS3IRVolumeUnready
    expr: lsi_sas_3_ir_volume_info{status !~ "Okay.*"} == 1
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: LSI SAS-3 volume is not ready. (instance {{ $labels.instance }})
      description: |
        LSI SAS-3 volume is not in "Okay" state. Please check the if the volume is working as expected.
          CONTROLLER_ID = {{ $labels.controller_id }}
          VOLUME_ID = {{ $labels.volume_id}}
          STATUS = {{ $labels.status }}
          LABELS = {{ $labels }}

  - alert: LSISAS3PhysicalDiskUnready
    expr: lsi_sas_3_physical_device_info{state !~ "(Ready.*|Optimal.*)"} == 1
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: LSI SAS-3 physical disk is not ready. (instance {{ $labels.instance }})
      description: |
        LSI SAS-3 physical disk not in "Ready" or "Optimal" state. Please check the if the physical disk is working as expected.
          CONTROLLER_ID = {{ $labels.controller_id }}
          ENCLOSURE_ID = {{ $labels.enclosure_id }}
          SLOT_ID = {{ $labels.slot_id }}
          STATE = {{ $labels.state }}
          LABELS = {{ $labels }}
